version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - env/.env.dev
    entrypoint: ""
    command: /root/docker-entrypoint-dev.sh
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.dev
    ports:
      - "5432:5432"

volumes:
  postgres_data:
