version: '3'

services:
  web:
    container_name: test_web
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres_test
      - DB_USER=postgres_test
      - DB_PASSWORD=postgres_test
      - SECRET_KEY=testsecretkey
      - ALGORITHM=HS256
      - FRONTEND_URL=http://127.0.0.1
    entrypoint: ""
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: test_db
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5432:5432"
