version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres_test
      - DB_USER=postgres_test
      - DB_PASSWORD=postgres_test
      - SECRET_KEY=testsecretkey
      - ALGORITHM=HS256
      - BACKEND_URL=http://127.0.0.1
    depends_on:
      db:
        condition: 'service_healthy'


  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
