FROM python:3.11.5-slim-bullseye

ENV PIP_DISABLE_PIP_VERSION_CHECK true
ENV PYTHONDONTWRITEBYTECODE true
ENV PYTHONUNBUFFERED true

WORKDIR /code

COPY ./requirements/requirements.prod.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.prod.txt

COPY . /code
EXPOSE 80

RUN useradd -ms /bin/bash maize-user
RUN chown -R maize-user:maize-user /code

ADD scripts/docker-entrypoint-prod.sh /home/maize-user/docker-entrypoint-prod.sh
ADD scripts/check_service.py /home/maize-user/check_service.py

RUN chmod +x /home/maize-user/docker-entrypoint-prod.sh
USER maize-user

ENTRYPOINT ["/home/maize-user/docker-entrypoint-prod.sh"]
